Initial PR
aligang/Gophkeeper pull request #1
Opened 2023-02-14 11:53 UTC by aligang

2023-02-19 12:44 UTC, kilchik requested changes

2023-02-19 12:44 UTC, kilchik commented on internal/pipeline/dispatcher/pipeline.go
> +package dispatcher
Я бы предложил сделать менее плоскую структуру пакетов. Сейчас неочевидно, какие пакеты относятся к клиенту, а какие к серверу. Из названия dispatcher непонятно, чем именно занимается пакет. Возможно имеет смысл разделить пакеты в /internal на /internal/client и /internal/server, а общие оставить в /internal/pkg или вынести в /pkg

2023-02-19 12:44 UTC, kilchik commented on internal/secret/handler/create.go
> +	logger.Debug("account id is: %s", accountID)
Увидел только дебаг-логи, нужны разные уровни логирования в зависимости от сообщения. Кроме того не все ошибки логируются, в ошибках особое внимание удели простановке всех необходимых атрибутов (например user_id) для того, чтобы по логам можно было проводить расследование ошибок

2023-02-19 12:44 UTC, kilchik commented on internal/secret/handler/create.go
> +		err = h.storage.WithinTransaction(ctx, func(ctx context.Context, tx *transaction.DBTransaction) error {
Создание транзакции для одной команды выглядит избыточно

2023-02-19 12:44 UTC, kilchik commented on internal/secret/handler/create.go
> +			return h.storage.AddTextSecret(ctx, s, tx)
Получается, что все данные в базе хранятся в plain text, т е при утечке базы злоумышленник сможет без проблем воспользоваться любыми паролями и банк картами. Так быть не должно, перед сохранением данных в базу их нужно хотя бы минимально шифровать/обфусцировать

2023-02-19 12:44 UTC, kilchik commented on internal/pipeline/dispatcher/pipeline.go
> +	conn, err := grpc.Dial(cfg.ServerAddress, grpc.WithTransportCredentials(insecure.NewCredentials()))
Пароли и банк карты - очень чувствительные данные, мы не можем позволить, чтобы они незащищенно передавались между клиентом и сервером, тут нужно использовать TLS

2023-02-20 14:42 UTC, aligang commented on internal/pipeline/dispatcher/pipeline.go
> +	conn, err := grpc.Dial(cfg.ServerAddress, grpc.WithTransportCredentials(insecure.NewCredentials()))
добавил TLS

2023-02-20 14:42 UTC, aligang commented on internal/secret/handler/create.go
> +			return h.storage.AddTextSecret(ctx, s, tx)
добавил шифрование в логику работы хендлеров

2023-02-20 14:43 UTC, aligang commented on internal/secret/handler/create.go
> +	logger.Debug("account id is: %s", accountID)
Расширил логирование

2023-02-20 14:43 UTC, aligang commented on internal/pipeline/dispatcher/pipeline.go
> +package dispatcher
структуру пакетов усложнил

2023-02-22 17:17 UTC, kilchik approved these changes

2023-02-22 23:01 UTC, merged